server:
  port: 80

logging:
    level:
      root: INFO

management:
  endpoints: 
    web:
      exposure:
        include: "*"
    
  endpoint:
    shutdown:
      enabled: true

netty:
  websocket:
    # Websocket服务端口
    port: 8080
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
#    max-content-length:


